### ISSUE TITLE
Evolve progress bar plugin

### ISSUE THREAD

**Issue by jim-gloaguen-zenika** [gouz/slidesk#100]
**Is your feature request related to a problem? Please describe.**
I would like to have a clear idea how many slides are remaining at any time during my presentation. I would also like to access a slide easily without having to go through all my slides.

**Describe the solution you'd like**
I would like the progress bar to be segmented depending the number of slides and hovering on a segment may display the slide's title and/or number. It would also be nice to have the possibilty of manually placing anchors/flags on the progress bar for quick access/having milestones.

**Comment by gouz** [comment]
https://github.com/gouz/slidesk/releases/tag/2.3.10 improves this progress bar with your suggestions thanks
