### ISSUE TITLE
Add numbers to the slides

### ISSUE THREAD

**Issue by jim-gloaguen-zenika** [gouz/slidesk#101]
**Describe the solution you'd like**
I would like to have my slides to have a number displayed on them. This would allow the public to easily ask questions about a specific slide.

**Comment by gouz** [comment]
{
    "addHTML": "<footer id='numslide' style='position: absolute; bottom: 5px; right: 5px; font-size: 1em;'></footer>",
    "onSlideChange": "document.getElementById('numslide').innerText = window.slidesk.currentSlide + 1;"
}

**Comment by gouz** [comment]
https://github.com/gouz/slidesk-extras/commit/5084edf5bd7b1d8db3b825835458e6cc41152cad
