### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by gouz** [gouz/slidesk#17]

**Comment by philippart-s** [comment]
Je me permets de mettre un peu de contexte en sachant que cela vient de moi 😉 :
 - basé sur ce qui est fait avec le plugin revealjs [internation](https://github.com/Martinomagnifico/reveal.js-internation)
 - en gros un fichier externe par langue pour un dictionnaire
 - puis une syntaxe permettant d'utiliser le placeholder dans la page
 - enfin le choix de la langue de manière statique ou dynamique

**Comment by gouz** [comment]
@philippart-s do you prefer writing the translation in the slide or a file apart ?

**Comment by gouz** [comment]
Something like BBcode

```
[en]Something in english[/en]
[fr]Quelque chose en français[/fr]
```

or more like variables and in file

```
$myTitle$



en.json

{
  "myTitle": "My Title"
}
```

**Comment by philippart-s** [comment]
Hi,
I prefer in a separate file, I found it more convenient to maintain

**Comment by gouz** [comment]
$myTitle$



en.json

{
  "default": true,
  "translations": {
    "myTitle": "My Title"
  }
}
