### ISSUE TITLE
[Bug] Wrong elements positioning when printing with Firefox

### ISSUE THREAD

**Issue by taorepoara** [gouz/slidesk#42]
When printing the slide with Firefox (to export to PDF), the slide elements are not well positioned.

![Capture d’écran du 2023-09-11 16-40-59](https://github.com/gouz/slidesk/assets/8969556/34b72b79-dd7d-4184-858d-1335e8dc5c49)

It works fine for Chromium based browsers.

**Comment by gouz** [comment]
fix with 1.6.6
