### ISSUE TITLE
[Core] Error after one page HTML generation (--save option)

### ISSUE THREAD

**Issue by philippart-s** [gouz/slidesk#76]
Step to reproduce: `slidesk --save`  
Expected behavior: slides fully usable  
What happen:
 - slides are stuck on the first slide
 - an error appear in the browser console:
```bash
Échec du chargement pour l’élément <script> dont la source est « file:///plugins/steps/steps.js ». [index.html:1:13009](file:///Users/stef/Talks/jarvis-slides/index.html)
Uncaught TypeError: window.slidesk.prepareSteps is not a function
    onSlideChange file:///Users/stef/Talks/jarvis-slides/index.html:1
    changeSlide file:///Users/stef/Talks/jarvis-slides/index.html:1
    onload file:///Users/stef/Talks/jarvis-slides/index.html:1
```

**Comment by gouz** [comment]
Hi, thanks for your issue. 
Like the assets (images, custom CSS or JS), the plugin directory must be copied in your destination with the HTML files

**Comment by philippart-s** [comment]
Ok I think I misunderstood the `--save` option!
The generated must be serve by a web server or can it open _as is_ in a browser?

**Comment by gouz** [comment]
Without plugin and customization, no need a webserver. Else you need to host

**Comment by philippart-s** [comment]
ok thanks I understood ;), the issue can be closed.
