### ISSUE TITLE
[Idea] Package core plugins in slidesk runtime

### ISSUE THREAD

**Issue by philippart-s** [gouz/slidesk#77]
Avoid download and maintain manually core plugins existing in the slidesk repository (https://github.com/gouz/slidesk/tree/main/plugins).  
Perhaps just a JSON config file to activate / deactivate the plugins:
```json
{
   "plugins":
     "steps": true,
     "gamepad": true
}
```

And when slidesk is updated no more need to update the plugins because they are updated with the core runtime.

Keep the possibility to create its own plugin by declaring it in the plugins folder is still a good idea :)

**Comment by gouz** [comment]
I think we can use the .env file which is readable since 2.1.15

**Comment by gouz** [comment]
The 2.2.0 version solves this issue
