### ISSUE TITLE
[Plugin] Add the possibility to use code from file in plugin declaration

### ISSUE THREAD

**Issue by philippart-s** [gouz/slidesk#82]
I'm not sure if this is already possible, if so, sorry.
It would be nice if the plugin declaration JSON file had a field to define a file instead of raw HTML.
The current JSON file has an attribute `addHTML` and if the code is larger or with lot of double quotes, it's not very easy to write it.

Perhaps add an attribute like `addHtmlFromFile` that allow to store the HTML code outside the JSON will be more pratical for some use cases :).

**Comment by gouz** [comment]
Nice Idea, currently the only way is to add raw HTML in addHTML

Will be present in the next version

**Comment by gouz** [comment]
code is in the `next` branch

**Comment by gouz** [comment]
Available in #84
